# Portainer Standalone (Non-Swarm) Deployment
# Deploy with: docker-compose -f portainer-compose.yml up -d
#
# This is a simpler deployment for single-node or non-swarm environments.
# For Docker Swarm clusters, use portainer-stack.yml instead.
#
# Access Portainer at: https://localhost:9443

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
      # OPTION 1: GlusterFS storage
      - /mnt/GlusterFS/Docker/Swarm/0001/data/Portainer:/data
      
      # OPTION 2: Local storage (uncomment if not using GlusterFS)
      # - portainer_data:/data

# Uncomment if using local storage (OPTION 2 above)
# volumes:
#   portainer_data:

