version: '3.8'

# Portainer Stack for Docker Swarm
# Deploy with: docker stack deploy -c portainer-stack.yml portainer
#
# This stack deploys:
# - Portainer Agent (global service on all nodes)
# - Portainer CE (replicated service on worker nodes)
#
# Requirements:
# - Docker Swarm initialized
# - Networks: DOCKER-SWARM-INTERNAL and DOCKER-SWARM-EXTERNAL must exist
# - GlusterFS mount at /mnt/GlusterFS/Docker/Swarm/0001/data (if using GlusterFS)
#
# Access Portainer at: https://<any-node-ip>:9443

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - DOCKER-SWARM-INTERNAL
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9443
        published: 9443
        protocol: tcp
        mode: ingress  # Routing mesh - accessible on any node
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress  # Edge agent tunnel
    volumes:
      # OPTION 1: GlusterFS storage (recommended for multi-node clusters)
      - /mnt/GlusterFS/Docker/Swarm/0001/data/Portainer:/data
      
      # OPTION 2: Local storage (uncomment if not using GlusterFS)
      # - portainer_data:/data
    networks:
      - DOCKER-SWARM-INTERNAL
      - DOCKER-SWARM-EXTERNAL
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker

networks:
  DOCKER-SWARM-INTERNAL:
    external: true
  DOCKER-SWARM-EXTERNAL:
    external: true

# Uncomment if using local storage (OPTION 2 above)
# volumes:
#   portainer_data:

