# NAME: PortainerAgent
# DESCRIPTION: Portainer Agent - Global service for Docker Swarm node management
# ENABLED: true
# NGINX_PROXY: false

services:
  PortainerAgent:
    image: portainer/agent:latest
    hostname: 'portainer-agent-{{.Node.ID}}'
    environment:
      AGENT_CLUSTER_ADDR: tasks.PortainerAgent
      LOG_LEVEL: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
      - /:/host:rw
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - EXTERNAL
      - INTERNAL
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux
      resources:
        limits:
          cpus: '8'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  EXTERNAL:
    name: DOCKER-SWARM-SERVICES-EXTERNAL
    external: true
  INTERNAL:
    name: DOCKER-SWARM-SERVICES-INTERNAL
    external: true

