# NAME: PortainerAgent
# DESCRIPTION: Portainer Agent - Global service for Docker Swarm node management
# ENABLED: true

services:
  portainer-agent:
    image: portainer/agent:latest
    hostname: 'portainer-agent-{{.Task.Slot}}'
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      LOG_LEVEL: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION:
    external: true

