# NAME: NginxUI
# DESCRIPTION: Nginx UI
# ENABLED: true

services:
  # Requires: docker node update --label-add loadbalancer.master=true <NODE>
  LoadBalancerMaster:
    image: uozi/nginx-ui:sha-4754ef3
    hostname: 'LoadBalancer-Master-{{.Task.Slot}}'
    environment:
      TZ: UTC
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI:/etc/nginx:rw
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI/nginx-ui:/etc/nginx-ui:rw
    networks:
      - DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux
          - node.role==worker
          - node.labels.loadbalancer.master==true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s

  # Serves traffic on ports 80/443, reads config from shared storage
  # Requires: docker node update --label-add loadbalancer.slave=true <NODE>
  LoadBalancerSlave:
    image: uozi/nginx-ui:sha-4754ef3
    hostname: 'LoadBalancer-Slave-{{.Task.Slot}}'
    environment:
      TZ: UTC
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI:/etc/nginx:ro
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI/nginx-ui:/etc/nginx-ui:ro
    networks:
      - DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux
          - node.role==worker
          - node.labels.loadbalancer.slave==true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s

networks:
  DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION:
    external: true

