# NAME: NginxUI
# DESCRIPTION: Nginx UI - Web-based Nginx management interface
# ENABLED: true

services:
  NginxUI:
    image: uozi/nginx-ui:sha-4754ef3
    hostname: 'Nginx-UI-{{.Task.Slot}}'
    environment:
      TZ: UTC
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI:/etc/nginx
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI/app:/app
    networks:
      - DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux
          - node.role==worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s

networks:
  DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION:
    external: true

