# NAME: Portainer
# DESCRIPTION: Container management UI for Docker Swarm
# ENABLED: true

version: '3.8'

services:
  portainer-agent:
    image: portainer/agent:latest
    hostname: 'portainer-agent-{{.Task.Slot}}'
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      LOG_LEVEL: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - DOCKER-SWARM-INTERNAL
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  portainer:
    image: portainer/portainer-ce:latest
    hostname: 'portainer-{{.Task.Slot}}'
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    environment:
      PORTAINER_AGENT_ADDR: tasks.portainer-agent
      LOG_LEVEL: INFO
    ports:
      - target: 9443
        published: 9443
        protocol: tcp
        mode: ingress
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    volumes:
      - /mnt/GlusterFS/Docker/Swarm/0001/data/Portainer:/data
    networks:
      - DOCKER-SWARM-INTERNAL
      - DOCKER-SWARM-EXTERNAL
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - node.role==worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s

networks:
  DOCKER-SWARM-INTERNAL:
    external: true
  DOCKER-SWARM-EXTERNAL:
    external: true

