#!/bin/bash
# 001-PreInitialization.sh - Runs before service deployment
# Environment variables available:
#   STORAGE_MOUNT_PATH     - Base storage mount path (e.g., /mnt/MicroCephFS/docker-swarm-0001)
#   SERVICE_DATA_DIR       - Service data subdirectory name (e.g., "data")
#   SERVICE_DEFINITIONS_DIR- Service definitions subdirectory name (e.g., "ServiceDefinitions")
#   PRIMARY_MASTER         - Primary master node hostname
#   HAS_DEDICATED_WORKERS  - "true" if cluster has dedicated workers
#   DISTRIBUTED_STORAGE    - "true" if distributed storage is enabled
#   NODE_HOSTNAME          - This node's hostname
#   NGINX_ENABLED          - "true" if Nginx service is enabled
#   NGINX_SERVICE_NAME     - Name of the Nginx service

set -e

echo "[PreInit] Starting pre-initialization..."
echo "[PreInit] STORAGE_MOUNT_PATH: ${STORAGE_MOUNT_PATH}"
echo "[PreInit] DISTRIBUTED_STORAGE: ${DISTRIBUTED_STORAGE}"
echo "[PreInit] NODE_HOSTNAME: ${NODE_HOSTNAME}"

# Exit early if no storage path configured
if [ -z "${STORAGE_MOUNT_PATH}" ]; then
    echo "[PreInit] No storage mount path configured, skipping pre-initialization"
    exit 0
fi

BASE_PATH="${STORAGE_MOUNT_PATH}/${SERVICE_DATA_DIR}"

# =============================================================================
# Nginx Pre-Initialization (Shared Config on Storage)
# =============================================================================

init_nginx_dirs() {
    local nginx_base="${BASE_PATH}/Nginx"
    local conf_path="${nginx_base}/conf"

    echo "[PreInit] Creating Nginx directories..."

    # Create all required directories
    mkdir -p "${conf_path}/conf.d"
    mkdir -p "${conf_path}/sites-enabled"
    mkdir -p "${conf_path}/stream.d"
    mkdir -p "${nginx_base}/ssl"
    mkdir -p "${nginx_base}/acme-challenge"

    # Download mime.types if not exists
    local mime_path="${conf_path}/mime.types"
    if [ ! -f "${mime_path}" ]; then
        curl -sSL -o "${mime_path}" 'https://raw.githubusercontent.com/nginx/nginx/master/conf/mime.types' 2>/dev/null || true
    fi

    # Create nginx.conf if not exists
    local nginx_conf="${conf_path}/nginx.conf"
    if [ ! -f "${nginx_conf}" ]; then
        cat > "${nginx_conf}" << 'NGINX_CONF_EOF'
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Include additional config files
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
NGINX_CONF_EOF
    fi

    # Create default server config if not exists
    local default_conf="${conf_path}/sites-enabled/default.conf"
    if [ ! -f "${default_conf}" ]; then
        cat > "${default_conf}" << 'DEFAULT_CONF_EOF'
# Default Server Configuration
# Generated by dscotctl - Edit via VSCode Server

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    # SSL configuration (self-signed placeholder until Certmate provisions certs)
    ssl_certificate /etc/nginx/ssl/default.crt;
    ssl_certificate_key /etc/nginx/ssl/default.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # ACME challenge for Certmate (Let's Encrypt)
    location /.well-known/acme-challenge/ {
        alias /etc/nginx/acme-challenge/;
        try_files $uri =404;
    }

    # Health check endpoint (for Docker Swarm)
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    # Default: 404
    location / {
        return 404;
    }
}
DEFAULT_CONF_EOF
    fi

    # Create self-signed default certificate if not exists
    local ssl_path="${nginx_base}/ssl"
    if [ ! -f "${ssl_path}/default.crt" ]; then
        if command -v openssl >/dev/null 2>&1; then
            echo "[PreInit] Generating self-signed default certificate..."
            openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
                -keyout "${ssl_path}/default.key" \
                -out "${ssl_path}/default.crt" \
                -subj "/CN=localhost" 2>/dev/null || true
        else
            echo "[PreInit] WARNING: openssl not found, skipping default certificate generation"
            echo "[PreInit] Install openssl or use Certmate to provision certificates"
        fi
    fi

    echo "[PreInit] Nginx directories ready"
}

# Initialize Nginx if enabled
if [ "${NGINX_ENABLED}" = "true" ]; then
    init_nginx_dirs
fi

# =============================================================================
# VSCode Server Pre-Initialization
# =============================================================================

echo "[PreInit] Initializing VSCode Server..."

VSCODE_PATH="${BASE_PATH}/VSCodeServer"
mkdir -p "${VSCODE_PATH}/config"
mkdir -p "${VSCODE_PATH}/config/workspace"
echo "[PreInit] VSCode Server directories created"

# =============================================================================
# Certmate Pre-Initialization
# =============================================================================

echo "[PreInit] Initializing Certmate..."

CERTMATE_PATH="${BASE_PATH}/Certmate"
mkdir -p "${CERTMATE_PATH}/data"
mkdir -p "${CERTMATE_PATH}/logs"
mkdir -p "${CERTMATE_PATH}/backups"

echo "[PreInit] Certmate directories created"

# =============================================================================
# Portainer Pre-Initialization
# =============================================================================
echo "[PreInit] Initializing Portainer..."

PORTAINER_PATH="${BASE_PATH}/Portainer"
mkdir -p "${PORTAINER_PATH}/data"
echo "[PreInit] Portainer directories created"

# =============================================================================
# Service Definitions Directory
# =============================================================================
echo "[PreInit] Creating ServiceDefinitions directory..."
mkdir -p "${STORAGE_MOUNT_PATH}/${SERVICE_DEFINITIONS_DIR}"
echo "[PreInit] ServiceDefinitions directory ready"

echo "[PreInit] ✅ Pre-initialization complete"

